name = "MyPackage"
uuid = "ddeabcdc-a339-40ff-99ae-b6f57c61f5aa"
authors = ["alex "]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
